spring:
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
  application:
    name: cloud-service
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
